#define _temp_swap_int(x, y) do{int temp=x;x=y;y=temp;}while(0)
#define _temp_swap_int_by_ptr(x, y) do{if(x!=y){int temp=*x;*x=*y;*y=temp;}}while(0)
#define _plus_min_swap_int(x, y) do{x+=y;y=x-y;x-=y;}while(0)
#define _plus_min_swap_int_by_ptr(x, y) do{if(x!=y){*x+=*y;*y=*x-*y;*x-=*y;}}while(0)
#define _alt_plus_min_swap_int(x, y) do{x=y-x;y-=x;x+=y;}while(0)
#define _alt_plus_min_swap_int_by_ptr(x, y) do{if(x!=y){*x=*y-*x;*y-=*x;*x+=*y;}}while(0)
#define _mul_div_swap_int(x, y) do{x*=y;y=x/y;x/=y;}while(0)
#define _mul_div_swap_int_by_ptr(x, y) do{if(x!=y){*x*=*y;*y=*x/(*y);*x/=*y;}}while(0)
#define _xor_swap_int(x, y) do{x^=y^=x^=y;}while(0)
#define _xor_swap_int_by_ptr(x, y) do{if(x!=y){*x^=*y^=*x^=*y;}}while(0)
